# Generated by Django 4.1.5 on 2023-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/guest-user_clv1cg_jztgdi', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='media/X43pV3x_flek8a', upload_to=''),
        ),
    ]
