# Generated by Django 4.1.5 on 2023-01-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipe_preparation_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
