# Generated by Django 4.1.5 on 2023-01-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_description_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default='media/OIP_xf4owa', upload_to=''),
        ),
    ]
